const assert=require('node:assert/strict');
const C=require('../daily-core.js');
const data=C.migrate({tasks:[],inbox:[{id:'legacy',text:'Conservare'}],goals:[{id:'goal',progress:18}],plannerBlocks:[{id:'event',title:'Evento precedente'}],unknown:{value:42}},'2026-10-09');
const input={kind:'task',text:'Ripassare inglese',area:'Studio',date:'2026-10-09',subject:'Inglese',priorityLevel:'home',reminder:true,reminderTime:'19:30'};
const id=C.writeEntry(data,input);
assert.equal(C.day(data,input.date).priorities[0],id);
assert.equal(C.day(data,input.date).tasks[0].subject,'Inglese');
C.toggle(data,input.date,id,'2026-10-09');
C.assign(data,'2026-10-08',data.tasks[0]);
const pastBefore=C.clone(C.day(data,'2026-10-08'));
C.writeEntry(data,{...input,text:'Ripassare vocaboli',priorityLevel:'high'},{taskId:id,recordDate:input.date});
assert.equal(C.day(data,input.date).tasks[0].completed,true);
assert.equal(C.day(data,input.date).tasks[0].reminderTime,'19:30');
assert.equal(C.day(data,input.date).priorities.length,0);
assert.deepEqual(C.day(data,'2026-10-08'),pastBefore);
assert.equal(data.tasks[0].title,'Ripassare vocaboli');
const noteId=C.writeEntry(data,{...input,kind:'note',priorityLevel:'normal',date:'2026-10-08',text:'Errori da rivedere'});
assert.equal(C.journal(data,'Studio',{kind:'note',date:'2026-10-08'})[0].entry.id,noteId);
C.writeEntry(data,{...input,kind:'note',priorityLevel:'low',date:'2026-10-07',text:'Nota corretta'},{entryId:noteId});
assert.equal(data.areaEntries[0].date,'2026-10-07');
assert.equal(data.areaEntries[0].subject,'Inglese');
assert.equal(C.journal(data,'Studio',{kind:'note',query:'corretta'})[0].date,'2026-10-07');
assert.throws(()=>C.writeEntry(data,{...input,kind:'idea'}),/priorità Home/);
assert.throws(()=>C.writeEntry(data,{...input,reminderTime:'25:00'}),/Ora/);
assert.throws(()=>C.writeEntry(data,{...input,date:'2026-02-30'}),/Data/);
assert.throws(()=>C.writeEntry(data,{...input,kind:'note',priorityLevel:'normal'},{taskId:id}),/tipo/);
assert.throws(()=>C.writeEntry(data,{...input,date:'2026-10-08'},{taskId:id,recordDate:'2026-10-09'}),/storico/);
for(let n=0;n<3;n++)C.writeEntry(data,{...input,text:'Priorità '+n});
const full=C.clone(data);
assert.throws(()=>C.writeEntry(data,{...input,text:'Quarta priorità'}),/tre priorità/);
assert.deepEqual(data,full);
const reload=C.migrate(C.clone(data),'2026-10-10');
assert.deepEqual(reload,data);
assert.deepEqual(data.inbox,[{id:'legacy',text:'Conservare'}]);
assert.deepEqual(data.goals,[{id:'goal',progress:18}]);
assert.deepEqual(data.plannerBlocks,[{id:'event',title:'Evento precedente'}]);
assert.equal(data.unknown.value,42);
console.log('PASS: new entry metadata, Home priorities, dated edits, historical checkmarks, notes on chosen dates, reminder validation, type guards, priority limit atomicity, reload and legacy fields.');
